-- MySQL Script generated by MySQL Workbench
-- Sun Sep 11 20:17:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema university_db
-- -----------------------------------------------------
USE `movies_db` ;

-- -----------------------------------------------------
-- Table `movies_db`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `dob` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`movies` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `rating` INT NULL,
  `runtime` TIME NULL,
  `genre` VARCHAR(255) NULL,
  `earnings_rank` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`actors` (
  `actor_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  INDEX `fk_persons_has_movies_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_persons_has_movies_persons_idx` (`actor_id` ASC) VISIBLE,
  PRIMARY KEY (`actor_id`, `movies_id`),
  CONSTRAINT `fk_persons_has_movies_persons`
    FOREIGN KEY (`actor_id`)
    REFERENCES `movies_db`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_has_movies_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `movies_db`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`directors` (
  `director_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  INDEX `fk_persons_has_movies_movies2_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_persons_has_movies_persons1_idx` (`director_id` ASC) VISIBLE,
  PRIMARY KEY (`director_id`, `movies_id`),
  CONSTRAINT `fk_persons_has_movies_persons1`
    FOREIGN KEY (`director_id`)
    REFERENCES `movies_db`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_has_movies_movies2`
    FOREIGN KEY (`movies_id`)
    REFERENCES `movies_db`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`oscars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`oscars` (
  `movies_id` INT NOT NULL,
  `persons_id` INT NOT NULL,
  `type` VARCHAR(255) NULL,
  `year` YEAR NULL,
  INDEX `fk_movies_has_persons_persons1_idx` (`persons_id` ASC) VISIBLE,
  INDEX `fk_movies_has_persons_movies1_idx` (`movies_id` ASC) VISIBLE,
  PRIMARY KEY (`persons_id`, `movies_id`),
  CONSTRAINT `fk_movies_has_persons_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `movies_db`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movies_has_persons_persons1`
    FOREIGN KEY (`persons_id`)
    REFERENCES `movies_db`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `office` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `capacity` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`courses` (
  `crn` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`crn`),
  INDEX `fk_courses_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `movies_db`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`majorsIns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`majorsIns` (
  `students_id` INT NOT NULL,
  `dept_id` INT NOT NULL,
  PRIMARY KEY (`students_id`, `dept_id`),
  INDEX `fk_students_has_departments_departments1_idx` (`dept_id` ASC) VISIBLE,
  INDEX `fk_students_has_departments_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_departments_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `movies_db`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_departments_departments1`
    FOREIGN KEY (`dept_id`)
    REFERENCES `movies_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies_db`.`enrolleds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies_db`.`enrolleds` (
  `students_id` INT NOT NULL,
  `courses_crn` INT NOT NULL,
  `credit_status` VARCHAR(45) NULL,
  PRIMARY KEY (`students_id`, `courses_crn`),
  INDEX `fk_students_has_courses_courses1_idx` (`courses_crn` ASC) VISIBLE,
  INDEX `fk_students_has_courses_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_courses_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `movies_db`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_courses_courses1`
    FOREIGN KEY (`courses_crn`)
    REFERENCES `movies_db`.`courses` (`crn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
